export type AsyncActionTypes<T extends string = string> = {
  REQUEST: `${T}#REQUEST`;
  SUCCESS: `${T}#SUCCESS`;
  FAILURE: `${T}#FAILURE`;
};

export const createAsyncActionTypes = <T extends string>(base: T): AsyncActionTypes<T> => ({
  REQUEST: `${base}#REQUEST`,
  SUCCESS: `${base}#SUCCESS`,
  FAILURE: `${base}#FAILURE`,
});

export const MUSIC_ACTIONS = {
  START_MUSIC: 'MUSIC.START_MUSIC',
  STOP_MUSIC: 'MUSIC.STOP_MUSIC',
  PAUSE_MUSIC: 'MUSIC.PAUSE_MUSIC',
  SEEK_MUSIC: 'MUSIC.SEEK_MUSIC',
  SEARCH_MUSIC: createAsyncActionTypes('MUSIC.SEARCH_MUSIC'),
  SET_LAST_SELECTED: 'MUSIC.SET_LAST_SELECTED',
  RESET_MUSIC: 'MUSIC.RESET_MUSIC',
  REMOVE_MUSIC: 'MUSIC.REMOVE_MUSIC',
  SET_CURRENT_OFFSET: 'MUSIC.SET_CURRENT_OFFSET',
  SET_GLOBAL_OFFSET: 'MUSIC.SET_GLOBAL_OFFSET',
  TRANSLATE_LYRIC: createAsyncActionTypes('MUSIC.TRANSLATE_LYRIC'),
} as const;

export const PREFERENCE_ACTIONS = {
  SET_DRAGGABLE: 'PREFERENCE.SET_DRAGGABLE',
  SET_LOCALE: 'PREFERENCE.LOCALE.SET_LOCALE',
  SET_PREFERENCE: 'PREFERENCE.SET_PREFERENCE',
  SET_PLAYER: createAsyncActionTypes('PREFERENCE.SET_PLAYER'),
} as const;

export const LAYOUT_ACTIONS = {
  SET_LAYOUT: 'LAYOUT.SET_LAYOUT',
  CLOSE_PREFERENCE: 'LAYOUT.CLOSE_PREFERENCE',
  RESIZE_WINDOW: 'LAYOUT.RESIZE_WINDOW',
  CHANGE_DRAGGABLE: 'LAYOUT.CHANGE_DRAGGABLE',
} as const;
